
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, AlertTriangle } from "lucide-react";
import { motion } from "framer-motion";

export default function DisclaimerPage() {
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-950 via-purple-900 to-pink-900 p-8">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl mx-auto"
      >
        <Button
          variant="ghost"
          onClick={() => setLocation("/auth")}
          className="mb-6 text-white hover:bg-white/10"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>

        <motion.div
          initial={{ scale: 0.9 }}
          animate={{ scale: 1 }}
          transition={{ type: "spring", stiffness: 200 }}
        >
          <Card className="bg-gray-900/80 backdrop-blur-xl border-purple-500/30">
            <CardHeader>
              <div className="flex items-center gap-3">
                <AlertTriangle className="w-10 h-10 text-yellow-500" />
                <CardTitle className="text-4xl font-bold bg-gradient-to-r from-cyan-400 via-blue-500 to-purple-600 bg-clip-text text-transparent">
                  Disclaimer
                </CardTitle>
              </div>
            </CardHeader>
            <CardContent className="space-y-4 text-gray-300">
              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.2 }}
                className="text-lg"
              >
                The information provided by EDITH ("we," "us," or "our") is for general informational purposes only.
              </motion.p>

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.3 }}
                className="space-y-3"
              >
                <h3 className="text-xl font-semibold text-white">No Warranty</h3>
                <p>
                  All information on EDITH is provided in good faith. However, we make no representation or warranty
                  of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, or completeness
                  of any information.
                </p>
              </motion.div>

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.4 }}
                className="space-y-3"
              >
                <h3 className="text-xl font-semibold text-white">AI-Generated Code</h3>
                <p>
                  Code generated by AI assistants should be reviewed and tested before use in production environments.
                  We are not responsible for any errors or issues arising from AI-generated code.
                </p>
              </motion.div>

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5 }}
                className="space-y-3"
              >
                <h3 className="text-xl font-semibold text-white">External Links</h3>
                <p>
                  EDITH may contain links to external websites. We have no control over and assume no responsibility
                  for the content, privacy policies, or practices of any third-party sites.
                </p>
              </motion.div>
            </CardContent>
          </Card>
        </motion.div>
      </motion.div>
    </div>
  );
}
